//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerModeChanger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string mode_Name_1 {
            get {
                return ((string)(this["mode_Name_1"]));
            }
            set {
                this["mode_Name_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mode_Name_2 {
            get {
                return ((string)(this["mode_Name_2"]));
            }
            set {
                this["mode_Name_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mode_Name_3 {
            get {
                return ((string)(this["mode_Name_3"]));
            }
            set {
                this["mode_Name_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mode_String_2 {
            get {
                return ((string)(this["mode_String_2"]));
            }
            set {
                this["mode_String_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mode_String_3 {
            get {
                return ((string)(this["mode_String_3"]));
            }
            set {
                this["mode_String_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string mode_String_1 {
            get {
                return ((string)(this["mode_String_1"]));
            }
            set {
                this["mode_String_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("To set")]
        public string sound_In_Mic1 {
            get {
                return ((string)(this["sound_In_Mic1"]));
            }
            set {
                this["sound_In_Mic1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("It Up")]
        public string sound_In_Mic2 {
            get {
                return ((string)(this["sound_In_Mic2"]));
            }
            set {
                this["sound_In_Mic2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visit")]
        public string sound_out_headphones1 {
            get {
                return ((string)(this["sound_out_headphones1"]));
            }
            set {
                this["sound_out_headphones1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings")]
        public string sound_out_headphones2 {
            get {
                return ((string)(this["sound_out_headphones2"]));
            }
            set {
                this["sound_out_headphones2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.8.8.8")]
        public string pingAdress {
            get {
                return ((string)(this["pingAdress"]));
            }
            set {
                this["pingAdress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pingNumberOfPingsLimited {
            get {
                return ((string)(this["pingNumberOfPingsLimited"]));
            }
            set {
                this["pingNumberOfPingsLimited"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pingNumberOfPingsUnlimited {
            get {
                return ((string)(this["pingNumberOfPingsUnlimited"]));
            }
            set {
                this["pingNumberOfPingsUnlimited"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string checkBox_power1 {
            get {
                return ((string)(this["checkBox_power1"]));
            }
            set {
                this["checkBox_power1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string checkBox_power2 {
            get {
                return ((string)(this["checkBox_power2"]));
            }
            set {
                this["checkBox_power2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string checkBox_power3 {
            get {
                return ((string)(this["checkBox_power3"]));
            }
            set {
                this["checkBox_power3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string checkBox_powerupdate {
            get {
                return ((string)(this["checkBox_powerupdate"]));
            }
            set {
                this["checkBox_powerupdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StateAutoPowerModeUpdate {
            get {
                return ((string)(this["StateAutoPowerModeUpdate"]));
            }
            set {
                this["StateAutoPowerModeUpdate"] = value;
            }
        }
    }
}
